// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ArenaAccessControl} from "./ArenaAccessControl.sol";
import {ReentrancyGuard} from "./ReentrancyGuard.sol";

interface IElementalRewards {
    function mintReward(address to, uint8 rewardLevel, bytes32 runId, string calldata tokenUri)
        external
        returns (uint256 tokenId);
}

/**
 * @title ElementalArena
 * @notice Holds entry fees and settles runs for Elemental RPS Arena.
 * @dev Round-by-round play stays off chain for cost and latency reasons. What
 *      the chain guarantees is the money path: an entry fee is paid once, a run
 *      settles exactly once, and a reward above the configured maximum can never
 *      be minted.
 *
 *      Settlement is authorised by an account holding SETTLER_ROLE — the game
 *      server. That trust boundary is explicit: this contract does not verify
 *      the game itself, it enforces that each run has one entry, one outcome,
 *      and one mint.
 */
contract ElementalArena is ArenaAccessControl, ReentrancyGuard {
    /// @notice Highest reward level the game recognises.
    uint8 public constant MAX_REWARD_LEVEL = 15;

    enum RunState {
        NONE,
        ENTERED,
        SETTLED_CLAIMED,
        SETTLED_LOST,
        REFUNDED
    }

    struct Run {
        address player;
        uint96 entryFee;
        bytes32 roomKey;
        RunState state;
        uint8 rewardLevel;
        uint64 enteredAt;
    }

    /// @notice Per-room entry fee in wei. Zero means the room is disabled.
    mapping(bytes32 => uint256) public entryFees;

    /// @notice Run id => run record.
    mapping(bytes32 => Run) public runs;

    /// @notice Per-player nonce, so a run id cannot be replayed by that player.
    mapping(address => uint256) public nonces;

    /// @notice Where collected entry fees are swept.
    address public treasury;

    /// @notice Rewards NFT contract.
    IElementalRewards public rewards;

    /// @notice Accumulated, unswept fees.
    uint256 public collectedFees;

    event GameEntered(bytes32 indexed runId, address indexed player, bytes32 indexed roomKey, uint256 entryFee, uint256 nonce);
    event RoundResolved(bytes32 indexed runId, uint16 roundNumber, uint8 levelAfter, bytes32 proofDigest);
    event RewardClaimed(bytes32 indexed runId, address indexed player, uint8 rewardLevel);
    event NFTMinted(bytes32 indexed runId, address indexed player, uint256 indexed tokenId, uint8 rewardLevel);
    event GameLost(bytes32 indexed runId, address indexed player, uint8 forfeitedLevel);
    event EntryFeeUpdated(bytes32 indexed roomKey, uint256 previousFee, uint256 newFee);
    event TreasuryUpdated(address indexed previousTreasury, address indexed newTreasury);
    event RewardsContractUpdated(address indexed previousRewards, address indexed newRewards);
    event FeesWithdrawn(address indexed to, uint256 amount);
    event RunRefunded(bytes32 indexed runId, address indexed player, uint256 amount);

    error RoomDisabled(bytes32 roomKey);
    error IncorrectEntryFee(uint256 expected, uint256 provided);
    error RunAlreadyExists(bytes32 runId);
    error RunNotFound(bytes32 runId);
    error RunAlreadySettled(bytes32 runId);
    error InvalidRewardLevel(uint8 level);
    error RewardsNotConfigured();
    error TransferFailed();
    error NothingToWithdraw();

    constructor(address admin, address treasury_) ArenaAccessControl(admin) {
        if (treasury_ == address(0)) revert ZeroAddress();
        treasury = treasury_;
    }

    // ------------------------------------------------------------- entry

    /**
     * @notice Pays the entry fee for a new run.
     * @param runId Opaque identifier generated by the server for this run.
     * @param roomKey keccak256 of the room key, e.g. keccak256("bronze").
     * @dev The player pays; the server does not custody funds. The exact fee is
     *      required — over- and underpayment both revert, so a client cannot
     *      choose its own price.
     */
    function enterGame(bytes32 runId, bytes32 roomKey) external payable whenNotPaused nonReentrant {
        uint256 fee = entryFees[roomKey];
        if (fee == 0) revert RoomDisabled(roomKey);
        if (msg.value != fee) revert IncorrectEntryFee(fee, msg.value);
        if (runs[runId].state != RunState.NONE) revert RunAlreadyExists(runId);

        uint256 nonce = nonces[msg.sender]++;

        runs[runId] = Run({
            player: msg.sender,
            entryFee: uint96(msg.value),
            roomKey: roomKey,
            state: RunState.ENTERED,
            rewardLevel: 0,
            enteredAt: uint64(block.timestamp)
        });

        collectedFees += msg.value;
        emit GameEntered(runId, msg.sender, roomKey, msg.value, nonce);
    }

    // -------------------------------------------------------- settlement

    /**
     * @notice Records a resolved round for auditability.
     * @dev Optional. Emitting every round on chain is expensive; the server may
     *      instead emit only the final settlement. The proof digest lets an
     *      observer tie an on-chain round back to the off-chain commit-reveal
     *      record.
     */
    function recordRound(bytes32 runId, uint16 roundNumber, uint8 levelAfter, bytes32 proofDigest)
        external
        onlyRole(SETTLER_ROLE)
        whenNotPaused
    {
        Run storage run = runs[runId];
        if (run.state == RunState.NONE) revert RunNotFound(runId);
        if (run.state != RunState.ENTERED) revert RunAlreadySettled(runId);
        if (levelAfter > MAX_REWARD_LEVEL) revert InvalidRewardLevel(levelAfter);

        run.rewardLevel = levelAfter;
        emit RoundResolved(runId, roundNumber, levelAfter, proofDigest);
    }

    /**
     * @notice Settles a run as claimed and mints the reward NFT to the player.
     * @dev The state transition happens before the external mint call, and the
     *      whole function is nonReentrant, so a malicious receiver cannot
     *      re-enter to claim twice.
     */
    function settleClaim(bytes32 runId, uint8 rewardLevel, string calldata tokenUri)
        external
        onlyRole(SETTLER_ROLE)
        whenNotPaused
        nonReentrant
    {
        Run storage run = runs[runId];
        if (run.state == RunState.NONE) revert RunNotFound(runId);
        if (run.state != RunState.ENTERED) revert RunAlreadySettled(runId);
        if (rewardLevel == 0 || rewardLevel > MAX_REWARD_LEVEL) revert InvalidRewardLevel(rewardLevel);
        if (address(rewards) == address(0)) revert RewardsNotConfigured();

        run.state = RunState.SETTLED_CLAIMED;
        run.rewardLevel = rewardLevel;

        emit RewardClaimed(runId, run.player, rewardLevel);

        uint256 tokenId = rewards.mintReward(run.player, rewardLevel, runId, tokenUri);
        emit NFTMinted(runId, run.player, tokenId, rewardLevel);
    }

    /// @notice Settles a run as lost. No reward is minted.
    function settleLoss(bytes32 runId, uint8 forfeitedLevel) external onlyRole(SETTLER_ROLE) whenNotPaused {
        Run storage run = runs[runId];
        if (run.state == RunState.NONE) revert RunNotFound(runId);
        if (run.state != RunState.ENTERED) revert RunAlreadySettled(runId);
        if (forfeitedLevel > MAX_REWARD_LEVEL) revert InvalidRewardLevel(forfeitedLevel);

        run.state = RunState.SETTLED_LOST;
        emit GameLost(runId, run.player, forfeitedLevel);
    }

    /**
     * @notice Refunds an entry fee for a run that could not be played.
     * @dev The escape hatch for server outages. State is written before the
     *      transfer, and the function is nonReentrant.
     */
    function refundRun(bytes32 runId) external onlyRole(OPERATOR_ROLE) nonReentrant {
        Run storage run = runs[runId];
        if (run.state == RunState.NONE) revert RunNotFound(runId);
        if (run.state != RunState.ENTERED) revert RunAlreadySettled(runId);

        uint256 amount = run.entryFee;
        run.state = RunState.REFUNDED;
        collectedFees -= amount;

        (bool ok,) = payable(run.player).call{value: amount}("");
        if (!ok) revert TransferFailed();
        emit RunRefunded(runId, run.player, amount);
    }

    // ----------------------------------------------------- configuration

    /// @notice Sets the entry fee for a room. Zero disables the room.
    function setEntryFee(bytes32 roomKey, uint256 fee) external onlyRole(ADMIN_ROLE) {
        uint256 previous = entryFees[roomKey];
        entryFees[roomKey] = fee;
        emit EntryFeeUpdated(roomKey, previous, fee);
    }

    /// @notice Points the arena at the rewards NFT contract.
    function setRewardsContract(address rewards_) external onlyRole(ADMIN_ROLE) {
        if (rewards_ == address(0)) revert ZeroAddress();
        emit RewardsContractUpdated(address(rewards), rewards_);
        rewards = IElementalRewards(rewards_);
    }

    /// @notice Updates the treasury address that receives swept fees.
    function setTreasury(address treasury_) external onlyRole(ADMIN_ROLE) {
        if (treasury_ == address(0)) revert ZeroAddress();
        emit TreasuryUpdated(treasury, treasury_);
        treasury = treasury_;
    }

    /// @notice Sweeps collected fees to the treasury.
    function withdrawFees() external onlyRole(ADMIN_ROLE) nonReentrant {
        uint256 amount = collectedFees;
        if (amount == 0) revert NothingToWithdraw();
        collectedFees = 0;

        (bool ok,) = payable(treasury).call{value: amount}("");
        if (!ok) revert TransferFailed();
        emit FeesWithdrawn(treasury, amount);
    }

    /// @notice Reads a run record.
    function getRun(bytes32 runId) external view returns (Run memory) {
        return runs[runId];
    }
}
